"""initial schema: 13 tables

Revision ID: d71df0fc3c3b
Revises: 
Create Date: 2026-08-05 21:30:19.434669
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71df0fc3c3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_gu', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('centroid', sa.JSON(), nullable=True),
    sa.Column('centroid_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_name', sa.String(length=128), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('macro_f1', sa.Float(), nullable=True),
    sa.Column('weighted_f1', sa.Float(), nullable=True),
    sa.Column('per_class', sa.JSON(), nullable=True),
    sa.Column('confusion_matrix', sa.JSON(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_runs_created_at'), ['created_at'], unique=False)

    op.create_table('golden_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('expected_department_code', sa.String(length=32), nullable=False),
    sa.Column('expected_secondary', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('golden_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golden_samples_expected_department_code'), ['expected_department_code'], unique=False)

    op.create_table('holidays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_date'), ['date'], unique=True)

    op.create_table('keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=256), nullable=False),
    sa.Column('term_normalized', sa.String(length=256), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keywords_term_normalized'), ['term_normalized'], unique=False)

    op.create_table('officers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('designation_en', sa.String(length=128), nullable=False),
    sa.Column('designation_gu', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officers_department_id'), ['department_id'], unique=False)

    op.create_table('sla_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('business_hours_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grievances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ref_no', sa.String(length=32), nullable=False),
    sa.Column('citizen_name', sa.String(length=128), nullable=False),
    sa.Column('citizen_email', sa.String(length=256), nullable=True),
    sa.Column('citizen_phone', sa.String(length=32), nullable=True),
    sa.Column('citizen_district', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('body_raw', sa.Text(), nullable=False),
    sa.Column('body_normalized', sa.Text(), nullable=True),
    sa.Column('detected_language', sa.String(length=8), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('secondary_department_ids', sa.JSON(), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decided_by_stage', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.String(length=4), nullable=True),
    sa.Column('assigned_officer_id', sa.String(length=36), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_message_id', sa.String(length=256), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grievances_citizen_district'), ['citizen_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_ref_no'), ['ref_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_grievances_sla_due_at'), ['sla_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_status'), ['status'], unique=False)

    op.create_table('action_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('officer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_tokens_grievance_id'), ['grievance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('classification_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('lexical_scores', sa.JSON(), nullable=True),
    sa.Column('lexical_hits', sa.JSON(), nullable=True),
    sa.Column('semantic_scores', sa.JSON(), nullable=True),
    sa.Column('fused_scores', sa.JSON(), nullable=True),
    sa.Column('arbiter_invoked', sa.Boolean(), nullable=False),
    sa.Column('arbiter_raw', sa.Text(), nullable=True),
    sa.Column('arbiter_parsed', sa.JSON(), nullable=True),
    sa.Column('chosen_department_code', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('decided_by_stage', sa.Integer(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=True),
    sa.Column('latency_ms', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_traces_grievance_id'), ['grievance_id'], unique=True)

    op.create_table('grievance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_label', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grievance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grievance_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievance_events_grievance_id'), ['grievance_id'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('suggested_department_id', sa.String(length=36), nullable=True),
    sa.Column('corrected_department_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrected_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.ForeignKeyConstraint(['suggested_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_grievance_id'), ['grievance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_grievance_id'))

    op.drop_table('review_queue')
    with op.batch_alter_table('grievance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grievance_events_grievance_id'))
        batch_op.drop_index(batch_op.f('ix_grievance_events_created_at'))

    op.drop_table('grievance_events')
    with op.batch_alter_table('classification_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_traces_grievance_id'))

    op.drop_table('classification_traces')
    with op.batch_alter_table('action_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_action_tokens_grievance_id'))

    op.drop_table('action_tokens')
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grievances_status'))
        batch_op.drop_index(batch_op.f('ix_grievances_sla_due_at'))
        batch_op.drop_index(batch_op.f('ix_grievances_ref_no'))
        batch_op.drop_index(batch_op.f('ix_grievances_department_id'))
        batch_op.drop_index(batch_op.f('ix_grievances_created_at'))
        batch_op.drop_index(batch_op.f('ix_grievances_citizen_district'))

    op.drop_table('grievances')
    op.drop_table('sla_policies')
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officers_department_id'))

    op.drop_table('officers')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_term_normalized'))
        batch_op.drop_index(batch_op.f('ix_keywords_department_id'))

    op.drop_table('keywords')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_date'))

    op.drop_table('holidays')
    with op.batch_alter_table('golden_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golden_samples_expected_department_code'))

    op.drop_table('golden_samples')
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_runs_created_at'))

    op.drop_table('eval_runs')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
